### ISSUE TITLE
Example Notebook Cleanup

### ISSUE THREAD

**Issue by ck090** [jakeret/unet#10]
Looks like the predictions are all completely masked to black images. I could replicate it on my end and got accurate predictions. I would love to fix it. <br>

**Comment by jakeret** [comment]
Do you mean the circle example? 
Your help is highly welcomed - could you send me a Pull Request to clean up the notebook?

**Comment by ck090** [comment]
Awesome! I'm working on it, will submit the Pull Request soon 🙌
