### ISSUE TITLE
What is the meaning of classes in Oxford Pets dataset?

### ISSUE THREAD

**Issue by lambdaofgod** [jakeret/unet#3]
In your code you write that there are 3 classes in the dataset. Where does it come from? On TF datasets page it says that there are 37 classes.

Also, what is the meaning of masks in the dataset? I've seen that there is only one channel for each mask so it isn't clear what should it mean for 3 classes

**Comment by jakeret** [comment]
The segmentation mask consists of 1) background-pixels, 2) animal-pixel and 3) animal-border-pixels. Hence 3 classes for this segmentation problem.

The 37 classes in the TF dataset refer to the classification problem where 37 different species have to be distinguished.
