### ISSUE TITLE
AttributeError: module 'unet' has no attribute 'build_model'`

### ISSUE THREAD

**Issue by maxclac** [jakeret/unet#9]
Hi!

While running the notebook 'oxford_pets.ipynb', I ran into the following issue:

`AttributeError                            Traceback (most recent call last)
<ipython-input-8-a6556caa6435> in <module>
      1 LEARNING_RATE = 1e-3
----> 2 unet_model = unet.build_model(*oxford_iiit_pet.IMAGE_SIZE,
      3                               channels=oxford_iiit_pet.channels,
      4                               num_classes=oxford_iiit_pet.classes,
      5                               layer_depth=5,

AttributeError: module 'unet' has no attribute 'build_model'`

What could it be?

Thanks!

**Comment by jakeret** [comment]
Hi @maxclac I just ran the local notebook and the the published collab notebook and in both cases it worked.
Have you installed the package using `pipenv install --dev`?
